import type { Metadata } from "next";
import Link from "next/link";
import { DocumentPage } from "@/components/public-site/document-page";

export const metadata: Metadata = {
  title: "Terms and Conditions | Crypto Index Asset",
  description: "Read the approved service terms, operator details, eligibility requirements, fees, and operational policies for Crypto Index Asset.",
};

export default function TermsPage() {
  return (
    <DocumentPage
      title="Terms and Conditions"
      intro="These Terms and Conditions govern your access to and use of the Crypto Index Asset platform, services, and associated applications. Please read these terms carefully before creating an account or committing funds."
      date="Effective 13 September 2026"
      sections={[
        {
          id: "operator",
          title: "1. Operator and Eligibility",
          content: (
            <>
              <p>
                The platform is operated by <strong>Crypto Index Asset Ltd</strong> (&ldquo;Crypto Index Asset&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;), a company incorporated in the United Kingdom (Company No. 14285910) with its registered office at 25 Bank Street, Canary Wharf, London E14 5JP, United Kingdom.
              </p>
              <p>
                To access and use the platform, you must satisfy the following criteria:
              </p>
              <ul>
                <li>Be at least 18 years of age and possess full legal capacity to enter into a binding agreement.</li>
                <li>Not be a resident, citizen, or located in any jurisdiction subject to comprehensive international sanctions or trade embargoes (including Cuba, Iran, North Korea, Syria, and the Crimea, Donetsk, or Luhansk regions of Ukraine).</li>
                <li>Not be listed on any applicable sanctions lists maintained by the UK HM Treasury, OFAC, European Union, or United Nations.</li>
                <li>Successfully complete our customer due diligence, identity verification, and anti-money laundering (AML) screening prior to transacting.</li>
              </ul>
            </>
          ),
        },
        {
          id: "account",
          title: "2. Account Registration and Security",
          content: (
            <>
              <p>
                You must provide accurate, current, and complete information during registration and keep your account profile updated. Each individual user may maintain only one verified personal account.
              </p>
              <p>
                You are solely responsible for maintaining the confidentiality of your credentials, including passwords, email verification tokens, and two-factor authentication (2FA) authenticator keys. You must immediately notify our security team at <code className="pp-code">security@cryptoindexasset.com</code> if you discover or suspect any unauthorized access or compromise of your credentials.
              </p>
              <p>
                Crypto Index Asset employees will never ask for your password, recovery phrase, or one-time verification codes under any circumstance.
              </p>
            </>
          ),
        },
        {
          id: "services",
          title: "3. Services and Copy-Trading Mechanics",
          content: (
            <>
              <p>
                Crypto Index Asset provides digital asset portfolio analytics, balance management, and automated trade-replication software (&ldquo;Copy Trading&rdquo;).
              </p>
              <p>
                When you initiate a copy-trading allocation to follow a featured trader:
              </p>
              <ul>
                <li>Your account parameters instruct automated software to mirror open and close signals generated by the selected trader in proportional ratio to your allocated balance.</li>
                <li>You acknowledge that copy trading is not individualized investment advice or discretionary portfolio management. You retain ultimate control and may pause, adjust, or terminate copy allocations at any time through your dashboard.</li>
                <li>Execution prices, execution timing, and slippage may vary between the master trader and your account due to market depth, network latency, and exchange queue conditions. We do not guarantee identical execution prices or replication parity.</li>
              </ul>
            </>
          ),
        },
        {
          id: "costs",
          title: "4. Fees, Charges, and High-Water Marks",
          content: (
            <>
              <p>
                All platform charges are governed by our public <Link href="/fees">Fee Schedule</Link>, which is incorporated into these terms by reference:
              </p>
              <ul>
                <li><strong>Account Maintenance:</strong> Free. We charge no account opening, monthly maintenance, or inactivity fees.</li>
                <li><strong>Deposit Fees:</strong> 0%. We do not levy fees on incoming crypto deposits (blockchain network transaction fees apply at the sender level).</li>
                <li><strong>Copy Trading Performance Fees:</strong> Successful copied strategies may incur a performance fee (typically 10% to 20%) calculated strictly on net new profits above the strategy&rsquo;s historical High-Water Mark (HWM). If an allocation incurs a net loss, no performance fee is charged until all prior losses are recovered.</li>
                <li><strong>Withdrawal Fees:</strong> Flat blockchain network processing fees apply to cover on-chain miner/gas costs per transfer. Rates are displayed transparently before confirmation.</li>
              </ul>
            </>
          ),
        },
        {
          id: "funding",
          title: "5. Deposits, Custody, and Withdrawals",
          content: (
            <>
              <p>
                Digital assets deposited to your account are accounted for on a strict double-entry ledger. User funds are segregated from our corporate operational capital.
              </p>
              <p>
                Before submitting a deposit, you must verify the destination address, network standard (e.g., ERC-20, TRC-20, Bitcoin native), and any required memo/tag. We are not liable for funds sent to incorrect addresses or over unsupported blockchain networks.
              </p>
              <p>
                Withdrawal requests require multi-factor verification and are subject to automated AML threshold checks. Standard withdrawals are processed within 1 hour; requests requiring enhanced compliance review are completed within 24 business hours.
              </p>
            </>
          ),
        },
        {
          id: "risk",
          title: "6. Investment and Digital Asset Risk",
          content: (
            <>
              <p>
                Trading and holding digital assets involves substantial risk of loss. Prices can fluctuate dramatically over short periods, and you may lose some or all of your invested capital.
              </p>
              <p>
                Past performance, historical win rates, and illustrated trader statistics are not a reliable indicator or guarantee of future returns. You should carefully review our comprehensive <Link href="/risk-disclosure">Risk Disclosure</Link> before allocating capital.
              </p>
            </>
          ),
        },
        {
          id: "closure",
          title: "7. Prohibited Conduct and Account Termination",
          content: (
            <>
              <p>
                You agree not to engage in market manipulation, wash trading, unauthorized scraping, reverse engineering, malicious vulnerability exploitation, or money laundering activities on the platform.
              </p>
              <p>
                You may close your account at any time by withdrawing your remaining balance and contacting support. We reserve the right to suspend, restrict, or terminate account access if we have reasonable grounds to suspect fraudulent activity, breach of these terms, or a violation of applicable financial sanctions.
              </p>
            </>
          ),
        },
        {
          id: "complaints",
          title: "8. Complaints, Governing Law, and Dispute Resolution",
          content: (
            <>
              <p>
                If you have an enquiry, grievance, or formal complaint, please submit it through our verified <Link href="/contact">contact form</Link> or email <code className="pp-code">complaints@cryptoindexasset.com</code>. We will assign a unique case reference and provide a formal written response within 15 business days.
              </p>
              <p>
                These Terms and any non-contractual obligations arising out of or in connection with them are governed by and construed in accordance with the laws of <strong>England and Wales</strong>.
              </p>
              <p>
                Any dispute arising out of or relating to these Terms shall first be submitted to good-faith mediation for a period of 30 days. If unresolved, disputes shall be subject to the exclusive jurisdiction of the competent courts of England and Wales.
              </p>
            </>
          ),
        },
        {
          id: "changes",
          title: "9. Amendments and Electronic Communications",
          content: (
            <>
              <p>
                We may modify these Terms to reflect regulatory changes, security enhancements, or new service offerings. We will provide at least 30 days advance notice of material amendments by posting an updated version on our website and transmitting an electronic notification to your registered email address.
              </p>
              <p>
                Your continued use of the platform after the effective date of an amendment constitutes your agreement to the modified Terms.
              </p>
            </>
          ),
        },
      ]}
    />
  );
}
